Add hint support for search request
vert-x3/vertx-mongo-client pull request #255
Opened 2021-04-26 07:22 UTC by leZudiste

Vertx mongo client doesn't support the hint() helper method and we need it to optimize our queries by using specific index.

2021-04-26 09:06 UTC, vietj commented on src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
> +    if (!options.getHint().isEmpty()) {
can you check nullity ?

2021-04-26 09:07 UTC, vietj requested changes
minor change

2021-04-26 09:11 UTC, tsegismont commented on src/main/generated/io/vertx/ext/mongo/FindOptionsConverter.java
> +    if (!obj.getHint().isEmpty()) {
It looks like you have modified this file manually. In this case, can you please run `mvn compile` and commit the generated files instead? Thank you

2021-05-05 06:01 UTC, leZudiste commented
Other modifications are necessary?

2021-05-05 12:57 UTC, merged

2021-05-05 12:57 UTC, vietj commented
thanks for the contribution