fix #296 Compression settings don't work.
vert-x3/vertx-mongo-client pull request #297
Opened 2023-02-21 13:42 UTC by irayce

Motivation:

fix #296 Compression settings don't work.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

2023-02-21 17:16 UTC, tsegismont requested changes
Thank you @tarvfx 

Can you please add:

- a test which shows config takes precedence over values in connection string
- documentation (in particular it should be said that the user must import a specific library for Snappy or Zstandard compression)
- a test which verifies connectivity with zlib compression

2023-02-21 17:16 UTC, tsegismont commented on src/main/java/io/vertx/ext/mongo/impl/config/CompressorListParser.java
> +    this.compressorKeys.add("zlibcompressionlevel");
Please change to camel case string

2023-02-21 17:16 UTC, tsegismont commented on src/main/java/io/vertx/ext/mongo/impl/config/CompressorListParser.java
> +  private final List<String> compressorKeys;
It's not necessary to create at runtime a list of keys for config. Instead, we can do with a couple of `if` statements in the `compressorList` method

2023-02-21 17:16 UTC, tsegismont commented on src/main/java/io/vertx/ext/mongo/impl/config/CompressorListParser.java
> +  private List<MongoCompressor> buildCompressors(final String compressors, @Nullable final Integer zlibCompressionLevel) {
Don't use `@Nullable` annotations in Vert.x code please

2023-02-21 17:16 UTC, tsegismont commented on src/main/java/io/vertx/ext/mongo/impl/config/CompressorListParser.java
> +        zlibCompressionLevel = Integer.parseInt(value);
Please catch the `NumberFormatException` and rethrow as `IllegalArgumentException` for consistency with other parsers

2023-02-21 17:16 UTC, tsegismont commented on src/main/java/io/vertx/ext/mongo/impl/config/CompressorListParser.java
> +    for (String cur : compressors.split(",")) {
We could be more tolerant and trim+lowercase each compressor name provided by users

2023-02-22 02:05 UTC, tarvfx commented
Hi, @tsegismont 

Thanks for your review and many suggestions. I'll fix these issues.

Regards

2023-02-22 07:21 UTC, tsegismont commented
Thank you!

2023-02-22 08:36 UTC, closed without merging

2023-02-22 09:11 UTC, tarvfx commented
@tsegismont I'm Sorry, this PR has to be abolished. I will submit it again.

2023-02-22 10:10 UTC, tarvfx commented
#298